// Auto-generated by flutter_rust_bridge. DO NOT EDIT.
// This is a placeholder. Run `flutter_rust_bridge_codegen generate` to generate the real bindings.

/// Wrapper for Rust-generated Dart bindings.
/// After codegen, this file will contain the actual generated code.
library;

export 'frb_generated.io.dart' if (dart.library.html) 'frb_generated.web.dart';
