// Auto-generated by flutter_rust_bridge. DO NOT EDIT.
// Placeholder for native IO bindings.
// Run `flutter_rust_bridge_codegen generate` to generate the real bindings.

import 'dart:ffi';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

// Placeholder - real bindings will be generated by flutter_rust_bridge_codegen
