// Auto-generated by flutter_rust_bridge. DO NOT EDIT.
// Placeholder for web bindings.
// Run `flutter_rust_bridge_codegen generate` to generate the real bindings.

// Placeholder - real bindings will be generated by flutter_rust_bridge_codegen
